"""add subscription fields

Revision ID: 02309c2d244e
Revises: be728b129da6
Create Date: 2026-01-14 07:43:17.814546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02309c2d244e'
down_revision = 'be728b129da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('subscription_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'trial'::character varying"))
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'trial'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
        batch_op.alter_column('subscription_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
        batch_op.drop_column('subscription_ends_at')

    # ### end Alembic commands ###
