"""add symptom templates

Revision ID: 07650aa4216d
Revises: 234b3e155ff9
Create Date: 2025-12-29 23:34:18.438638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07650aa4216d'
down_revision = '234b3e155ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.create_unique_constraint(
    "uq_prescription_template_clinic_owner_name",
    ['clinic_owner_id', 'name']
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
