"""add prescription templates

Revision ID: 234b3e155ff9
Revises: a22d376567d2
Create Date: 2025-12-29 01:23:27.304313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234b3e155ff9'
down_revision = 'a22d376567d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_template_clinic_owner_id'), ['clinic_owner_id'], unique=False)

    op.create_table('prescription_template_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['prescription_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prescription_template_item')
    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_template_clinic_owner_id'))

    op.drop_table('prescription_template')
    # ### end Alembic commands ###
