"""remove appointment prescription text column

Revision ID: 2819ddb9c9f9
Revises: ac3ced79df81
Create Date: 2025-12-23 01:03:19.584330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2819ddb9c9f9'
down_revision = 'ac3ced79df81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('prescription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescription', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
