"""performance indexes

Revision ID: 4bf0f736c4c4
Revises: badbb2f17972
Create Date: 2026-01-07 08:18:56.074621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf0f736c4c4'
down_revision = 'badbb2f17972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index('idx_appt_clinic_date', ['clinic_id', 'date'], unique=False)
        batch_op.create_index('idx_appt_clinic_status', ['clinic_id', 'status'], unique=False)
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('invoice_sequence', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('prescription_appointment_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_prescription_appointment_id'), ['appointment_id'], unique=True)

    with op.batch_alter_table('prescription_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_item_prescription_id'), ['prescription_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('prescription_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_item_prescription_id'))

    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_appointment_id'))
        batch_op.create_unique_constraint(batch_op.f('prescription_appointment_id_key'), ['appointment_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice_sequence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_appt_clinic_status')
        batch_op.drop_index('idx_appt_clinic_date')

    # ### end Alembic commands ###
