"""remove clinic fields from user

Revision ID: 63dc3daa44b2
Revises: 7edb4ac6f356
Create Date: 2026-01-01 10:36:01.923841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dc3daa44b2'
down_revision = '7edb4ac6f356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clinic_phone')
        batch_op.drop_column('clinic_name')
        batch_op.drop_column('clinic_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_address', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clinic_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clinic_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
