"""soft delete enabled

Revision ID: 84949f3d9485
Revises: 2819ddb9c9f9
Create Date: 2025-12-23 19:59:21.390690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84949f3d9485'
down_revision = '2819ddb9c9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointment_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invoice_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patient_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_is_deleted'))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_is_deleted'))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_is_deleted'))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
