"""add lab_tests to appointment

Revision ID: a22d376567d2
Revises: 84949f3d9485
Create Date: 2025-12-29 00:57:42.636255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22d376567d2'
down_revision = '84949f3d9485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_tests', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('lab_tests')

    # ### end Alembic commands ###
