"""cleanup clinic ownership

Revision ID: a61a3307fe6c
Revises: 63dc3daa44b2
Create Date: 2026-01-01 10:38:29.097769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61a3307fe6c'
down_revision = '63dc3daa44b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_invoice_item_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinic_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_payment_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_clinic_id'))
        batch_op.drop_column('clinic_id')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoice_item_clinic_id'))
        batch_op.drop_column('clinic_id')

    # ### end Alembic commands ###
