"""add clinic table and clinic_id columns

Revision ID: badbb2f17972
Revises: 9b90cdeced15
Create Date: 2026-01-02 20:30:10.325004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badbb2f17972'
down_revision = '9b90cdeced15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('prescription_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'name')
    )
    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_template_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('symptom_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_template_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['prescription_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('appointment', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('audit_log', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('invoice', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('invoice_item', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('invoice_sequence', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('medical_record', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('patient', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('payment', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])

    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'clinic', ['clinic_id'], ['id'])
    # with op.batch_alter_table('clinic', schema=None) as batch_op:
    #     batch_op.create_foreign_key(
    #         'fk_clinic_owner_user',
    #         'user',
    #         ['owner_id'],
    #         ['id']
    #     )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('medical_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice_sequence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('prescription_template_item')
    op.drop_table('symptom_template')
    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_template_clinic_id'))

    op.drop_table('prescription_template')
    op.drop_table('clinic')
    # ### end Alembic commands ###
