"""add symptom templates

Revision ID: c9fd5adf3d01
Revises: 234b3e155ff9
Create Date: 2025-12-29 23:24:53.954681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fd5adf3d01'
down_revision = '234b3e155ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptom_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptom_template_clinic_owner_id'), ['clinic_owner_id'], unique=False)

    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['clinic_owner_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_template', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('symptom_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_template_clinic_owner_id'))

    op.drop_table('symptom_template')
    # ### end Alembic commands ###
