"""add user document fields

Revision ID: f41fbc4291d1
Revises: a61a3307fe6c
Create Date: 2026-01-01 10:44:20.854803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41fbc4291d1'
down_revision = 'a61a3307fe6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('aadhar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mrc_certificate', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('clinic_license', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('clinic_license')
        batch_op.drop_column('mrc_certificate')
        batch_op.drop_column('aadhar')
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
